flags:
  jigjs:
    paths:
      - jig/**/*
    carryforward: true
  jigcss:
    paths:
      - jigcss/**/*
    carryforward: false

coverage:
  status:
    project:
      jigjs:
        target: auto
        flags:
          - jigjs
      jigcss:
        target: auto
        flags:
          - jigcss