coverage:
  status:
    project:
      jig:
        target: auto
        flags:
          - jig/**/*
        paths: 
          - jigcss/**/*
      jigcss:
        target: auto
        flags:
          - jigcss
        paths: 
          - jigcss
flags:
  jig:
    paths:
      - jig/**/*
  jigcss:
    paths:
      - jigcss/**/*
    joined: true