coverage:
  status:
    project:
      jig:
        target: auto
        flags:
          - jig
        paths: 
          - jig
      jigcss:
        target: auto
        flags:
          - jigcss
        paths: 
          - jigcss
flags:
  jig:
    paths:
      - jig/**/*
    carryforward: true
  jigcss:
    paths:
      - jigcss/**/*
    joined: true