# Generated by Django 3.0.5 on 2020-04-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('primary_type', models.CharField(max_length=60)),
                ('secondary_type', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_atk', models.IntegerField()),
                ('sp_def', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('generation', models.IntegerField()),
                ('legendary', models.BooleanField()),
            ],
        ),
    ]
