# This is a basic workflow to help you get started with Actions

name: Jig
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install yarn
    - run: yarn --cwd jig
      env:
        CI: true
    - run: yarn --cwd jig clean
      env:
        CI: true
    - run: yarn --cwd jig lint
      env:
        CI: true
    - run: yarn --cwd jig test:coverage
      env:
        CI: true
    - run: npm install yarn
    - run: yarn --cwd jigcss
      env:
        CI: true
    - run: yarn --cwd jigcss clean
      env:
        CI: true
    - run: yarn --cwd jigcss lint
      env:
        CI: true
    - run: yarn --cwd jigcss test:coverage
      env:
        CI: true
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./jig/coverage/lcov.info
        flags: jig
        fail_ci_if_error: true
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./jigcss/coverage/lcov.info
        flags: jigcss
        fail_ci_if_error: true